# Generated by Django 6.0.2 on 2026-07-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default-cover.jpg', null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.ImageField(blank=True, default='avatars/default-avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
